# Generated by Django 5.1.2 on 2024-10-22 20:13

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('dec_id', models.AutoField(primary_key=True, serialize=False)),
                ('dec_date', models.DateField()),
                ('dec_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/decree/')),
                ('attach', models.FileField(blank=True, upload_to='attach/decree/')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('inc_id', models.AutoField(primary_key=True, serialize=False)),
                ('orig_date', models.DateField()),
                ('reg_date', models.DateField()),
                ('orig_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_number', models.CharField(max_length=100)),
                ('dept_from', models.CharField(max_length=100)),
                ('dept_to', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/incoming/')),
                ('attach', models.FileField(blank=True, upload_to='attach/incoming')),
            ],
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('int_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_date', models.DateField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_from', models.CharField(max_length=100)),
                ('dept_to', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/internal/')),
                ('attach', models.FileField(blank=True, upload_to='attach/internal/')),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('out_id', models.AutoField(primary_key=True, serialize=False)),
                ('out_date', models.DateField()),
                ('reg_number', models.CharField(max_length=100)),
                ('dept_from', models.CharField(max_length=100)),
                ('dept_to', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to=documents.models.get_pdf_upload_path)),
                ('attach', models.FileField(blank=True, upload_to=documents.models.get_attach_upload_path)),
            ],
        ),
    ]
