# Generated by Django 5.1.3 on 2024-12-20 15:38

import django.core.validators
import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_attached', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'الجهة',
                'verbose_name_plural': 'الجهات',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'الادارة او المكتب',
                'verbose_name_plural': 'الادارات و المكاتب',
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'الحكومة',
                'verbose_name_plural': 'الحكومات',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Enter a valid number with dashes or slashes.', regex='^[0-9/-]*$')])),
                ('orig_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Enter a valid number with dashes or slashes.', regex='^[0-9/-]*$')])),
                ('date', models.DateField()),
                ('orig_date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_affiliates', to='documents.affiliate')),
                ('deptartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_departments', to='documents.department')),
            ],
            options={
                'verbose_name': 'بريد وارد',
                'verbose_name_plural': 'البريد الوارد',
            },
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deptartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_departments_from', to='documents.department')),
                ('deptartment_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_departments_to', to='documents.department')),
            ],
            options={
                'verbose_name': 'مذكرة داخلية',
                'verbose_name_plural': 'المذكرات الداخلية',
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('government', models.ManyToManyField(related_name='minister_on_duty', to='documents.government')),
            ],
            options={
                'verbose_name': 'الوزير',
                'verbose_name_plural': 'الوزراء',
            },
        ),
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('attach', models.FileField(blank=True, upload_to=documents.models.get_attach_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decrees', to='documents.government')),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decrees', to='documents.minister')),
            ],
            options={
                'verbose_name': 'قرار',
                'verbose_name_plural': 'القرارات',
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Enter a valid number with dashes or slashes.', regex='^[0-9/-]*$')])),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_affiliates', to='documents.affiliate')),
                ('deptartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_departments', to='documents.department')),
            ],
            options={
                'verbose_name': 'بريد صادر',
                'verbose_name_plural': 'البريد الصادر',
            },
        ),
    ]
