# Generated by Django 5.1.2 on 2024-10-24 15:03

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decree',
            old_name='dec_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='incoming',
            old_name='inc_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='internal',
            old_name='int_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='outgoing',
            old_name='out_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='decree',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/decree/'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/incoming/'),
        ),
        migrations.AlterField(
            model_name='internal',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/internal/'),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path),
        ),
    ]
