# Generated by Django 5.1.2 on 2024-11-15 11:32

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='internal',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='attach',
        ),
        migrations.AlterField(
            model_name='decree',
            name='attach',
            field=models.FileField(blank=True, upload_to=documents.models.get_attach_upload_path),
        ),
        migrations.AlterField(
            model_name='decree',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='internal',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path),
        ),
    ]
