# Generated by Django 5.1.3 on 2024-12-20 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['-created_at'], 'verbose_name': 'الجهة', 'verbose_name_plural': 'الجهات'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at'], 'verbose_name': 'الادارة او المكتب', 'verbose_name_plural': 'الادارات و المكاتب'},
        ),
        migrations.AlterModelOptions(
            name='government',
            options={'ordering': ['-created_at'], 'verbose_name': 'الحكومة', 'verbose_name_plural': 'الحكومات'},
        ),
        migrations.AlterModelOptions(
            name='minister',
            options={'ordering': ['-created_at'], 'verbose_name': 'الوزير', 'verbose_name_plural': 'الوزراء'},
        ),
        migrations.AddField(
            model_name='affiliate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='government',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='government',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='minister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
