# Generated by Django 5.1.2 on 2024-11-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_incoming_attach_remove_internal_attach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decree',
            name='dec_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='decree',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='orig_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='reg_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internal',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='internal',
            name='reg_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='reg_number',
            field=models.CharField(max_length=10),
        ),
    ]
