# Generated by Django 5.1.3 on 2024-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_minister_government_alter_incoming_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='is_attached',
            field=models.BooleanField(default=False),
        ),
    ]
