# Generated by Django 5.1.3 on 2024-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_decree_keywords_alter_incoming_orig_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='minister',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
