# Generated by Django 5.1.3 on 2024-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_decree_number_alter_internal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='decree',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incoming',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
