# Generated by Django 5.1.3 on 2024-11-23 23:24

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_decree_deleted_at_incoming_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True, max_length=999)),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.get_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
