# Generated by Django 5.1.3 on 2024-11-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minister',
            name='government',
        ),
        migrations.AddField(
            model_name='minister',
            name='government',
            field=models.ManyToManyField(related_name='minister_on_duty', to='documents.government'),
        ),
    ]
